### ISSUE TITLE
You should consider using okcupyd

### ISSUE THREAD

**Issue by IvanMalison** [kleprevost/okscrape#1]
Shameless self plug, but okcupyd could make a lot of the work your doing here much easier:

https://github.com/IvanMalison/okcupyd

**Comment by kleprevost** [comment]
Yep, your library is actually pretty amazing. To be honest okscrape started out as a fun project to learn Python and has slowly evolved from there - since I hit my "goal" I may just switch this over to use your libraries. How do you handle changes to OKC's HTML structure? They have changed up div names a couple times on me since I started poking around with this.

**Comment by IvanMalison** [comment]
Yeah its super annoying. I have a whole test suite in okcupyd that can be run against the live website with a keyword argument (usually the test suite mocks out http interactions with vcrpy). I could probably get that working in CI pretty easily, but I just havent gotten around to it.

Typically, my code is general enough that it just means tweaking a string here or there.

There are a few unresolved reports of certain details not working. If you want to take a crack at fixing them, it would be greatly appreciated.
